### ISSUE TITLE
Plan out the Activity creation flow chart

### ISSUE THREAD

**Issue by Spottyboy** [SpotswoodCollege/eotc-helper#22]
Plan out a flow chart for the creation of Activities.

**Comment by microlith57** [comment]
@Spottyboy got these:
[Management Guide Tree.pdf](https://github.com/SpotswoodCollege/eotc-helper/files/2230363/Management.Guide.Tree.pdf)
[Management Guide.pdf](https://github.com/SpotswoodCollege/eotc-helper/files/2230364/Management.Guide.pdf)
[Volunteer Descriptions.pdf](https://github.com/SpotswoodCollege/eotc-helper/files/2230365/Volunteer.Descriptions.pdf)
